
package com.fedex.ws.ship.v15;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShipPortType", targetNamespace = "http://fedex.com/ws/ship/v15")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShipPortType {


    /**
     * 
     * @param processTagRequest
     * @return
     *     returns com.fedex.ws.ship.v15.ProcessTagReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v15/processTag")
    @WebResult(name = "ProcessTagReply", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "ProcessTagReply")
    public ProcessTagReply processTag(
        @WebParam(name = "ProcessTagRequest", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "ProcessTagRequest")
        ProcessTagRequest processTagRequest);

    /**
     * 
     * @param processShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v15.ProcessShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v15/processShipment")
    @WebResult(name = "ProcessShipmentReply", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "ProcessShipmentReply")
    public ProcessShipmentReply processShipment(
        @WebParam(name = "ProcessShipmentRequest", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "ProcessShipmentRequest")
        ProcessShipmentRequest processShipmentRequest);

    /**
     * 
     * @param deleteTagRequest
     * @return
     *     returns com.fedex.ws.ship.v15.ShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v15/deleteTag")
    @WebResult(name = "ShipmentReply", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "ShipmentReply")
    public ShipmentReply deleteTag(
        @WebParam(name = "DeleteTagRequest", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "DeleteTagRequest")
        DeleteTagRequest deleteTagRequest);

    /**
     * 
     * @param deleteShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v15.ShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v15/deleteShipment")
    @WebResult(name = "ShipmentReply", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "ShipmentReply")
    public ShipmentReply deleteShipment(
        @WebParam(name = "DeleteShipmentRequest", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "DeleteShipmentRequest")
        DeleteShipmentRequest deleteShipmentRequest);

    /**
     * 
     * @param validateShipmentRequest
     * @return
     *     returns com.fedex.ws.ship.v15.ShipmentReply
     */
    @WebMethod(action = "http://fedex.com/ws/ship/v15/validateShipment")
    @WebResult(name = "ShipmentReply", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "ShipmentReply")
    public ShipmentReply validateShipment(
        @WebParam(name = "ValidateShipmentRequest", targetNamespace = "http://fedex.com/ws/ship/v15", partName = "ValidateShipmentRequest")
        ValidateShipmentRequest validateShipmentRequest);

}
